# -*- coding: utf-8 -*-
"""Analisis portafolio 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbE3qqurj9Ih2uEIxucmdTRFTn7zgUmM
"""

# -*- coding: utf-8 -*-
"""Aplicacion portafolio con ticker"""

import streamlit as st
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

st.title('ANÁLISIS DE PORTAFOLIO DE INVERSIÓN')
st.subheader('Ejemplo de diversificación con dos acciones')

# Selección de acciones
tickers = ['AAPL', 'KO']  # Apple y Coca-Cola
st.write("Acciones seleccionadas:", tickers)

# Descargar datos desde Yahoo Finance
data = yf.download(tickers, start='2022-01-01', end='2025-01-01')['Adj Close']

# Mostrar tabla de precios
st.subheader("Precios históricos ajustados")
st.dataframe(data.tail())

# Calcular rendimientos diarios
returns = data.pct_change().dropna()

# Mostrar resumen estadístico
st.subheader("Estadísticas de rentabilidad diaria")
st.write(returns.describe())

# Gráfico de precios
st.subheader("Evolución del precio de las acciones")
fig, ax = plt.subplots()
data.plot(ax=ax)
st.pyplot(fig)

# Gráfico de dispersión entre los rendimientos (para ver correlación)
st.subheader("Relación entre los rendimientos (correlación)")
fig2, ax2 = plt.subplots()
ax2.scatter(returns['AAPL'], returns['KO'], alpha=0.6)
ax2.set_xlabel('Rendimiento AAPL')
ax2.set_ylabel('Rendimiento KO')
ax2.set_title('Diversificación entre Apple y Coca-Cola')
st.pyplot(fig2)

# Calcular correlación
correlacion = returns.corr()
st.subheader("Matriz de correlación")
st.write(correlacion)

# Interpretación
st.markdown("""
**Interpretación:**
Si la correlación entre AAPL y KO es baja o negativa, significa que las acciones no se mueven igual:
cuando una baja, la otra puede subir o mantenerse estable.
Esto **reduce el riesgo total** del portafolio y muestra la ventaja de la **diversificación**.
""")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit yfinance matplotlib pandas