# -*- coding: utf-8 -*-
"""Aplicacion_portafolio pynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/blankchechi26-alt/Borradores-Portafolio/blob/main/Aplicacion_portafolio%20pynb.ipynb
"""

import streamlit as st
import pandas as pd

st.title('ANÁLISIS DE PORTAFOLIO DE INVERSIÓN')

st.markdown('**INTEGRANTES DEL GRUPO**')

st.markdown('Andrea Velasquez')

st.markdown('Blanca Alvarez')

Temas=['Definición','Tipos de analisis de portafolio', 'Selección de la propuesta', 'Herramienta', 'Referencias']

Tema_seleccionado=st.selectbox('selecciona un tema;', Temas)

st.write('Has seleccionado:', Tema_seleccionado)



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# st.title('ANÁLISIS DE PORTAFOLIO DE INVERSIÓN')
# st.markdown('**INTEGRANTES DEL GRUPO**')
# st.markdown('Andrea Velasquez')
# st.markdown('Blanca Alvarez')
# 
# Temas=['Definición','Tipos de analisis de portafolio', 'Selección de la propuesta', 'Herramienta', 'Referencias']
# Tema_seleccionado=st.selectbox('selecciona un tema;', Temas)
# st.write('Has seleccionado:', Tema_seleccionado)
# 
# if Tema_seleccionado=='Definición':
#     st.markdown('''**ANÁLISIS DE PORTAFOLIO DE INVERSIÓN:**
# 
# Un Análisis de Portafolio de Inversión consiste en estudiar y evaluar el conjunto de activos financieros (acciones, bonos, bienes raíces, entre otros) en el que una persona o empresa ha invertido. El objetivo de este análisis es entender cómo se comportan esos activos, tanto en términos de riesgo como de rentabilidad.
# 
# **Principios elementales de inversión**.
# En todo instrumento financiero de un portafolio de inversión tienen
# que considerarse los siguientes elementos:
# 
# - ***Rendimiento***: Es la ganancia que se obtendría y está dada en función a la tasa y al plazo de inversión.
# 
# Es la estimación de las ganancias que se espera obtener de las inversiones a lo largo del tiempo. Este rendimiento puede variar dependiendo de las condiciones del mercado, but is important to project it to make informed decisions.
# 
# - ***Riesgo***: Se refiere a la posibilidad de que los rendimientos no se den como se esperaba. En este contexto, se suelen usar herramientas estadísticas como la volatilidad (que mide las fluctuaciones de los precios de los activos), la varianza y la desviación estándar para cuantificar cuán impredecibles o inestables son los rendimientos.
# 
# Debe determinarse cuánto riesgo se está dispuesto a asumir.
# 
# - ***Diversificación y correlación***: Uno de los principios clave en la gestión de un portafolio es diversificar. Esto significa invertir en diferentes tipos de activos que no se muevan de manera idéntica. La correlación entre los activos muestra si sus rendimientos tienden a moverse juntos o en direcciones opuestas. Idealmente, se buscan activos con baja correlación entre sí, para reducir el riesgo total del portafolio.
# 
# Es decir, en lugar de invertir todo el capital en un solo activo (como, por ejemplo, solo en acciones de una empresa), se distribuye entre diferentes activos, clases de activos o mercados. Al hacer esto, se busca minimizar el impacto de los posibles rendimientos negativos de un asset específico.
# 
# - ***Relación riesgo-retorno***: Un análisis de portafolio también evalúa si el rendimiento que se espera obtener justifica el riesgo que se asume. Es decir, busca encontrar un balance entre obtener buenos rendimientos sin exponerse a un riesgo excesivo.
# 
# **En resumen**, Un portafolio de inversión es un conjunto de activos financieros que se combinan para generar rendimientos con un nivel de riesgo controlado. La diversificación busca repartir el dinero entre diferentes activos para reducir riesgos, mientras que la correlación mide cómo se comportan esos activos entre sí. El objetivo is to balance risk and return to optimize gains.
# 
# Es una herramienta crucial para los inversionistas que buscan maximizar su rentabilidad y minimizar los riesgos asociados con sus decisiones financieras.''')
# elif Tema_seleccionado=='Tipos de analisis de portafolio':
#     st.markdown('''**TIPOS DE ANALISIS DE PORTAFOLIO:**
# ***Presentamos las siguientes propuestas:***
# 
# **Propuesta 1:**
# 
# **Optimización de portafolio: Frontera eficiente**
# 
# La frontera eficiente es un concepto clave en la optimización de portafolios de inversión. Se refiere a la combinación ideal de activos que te permite maximizar el rendimiento para un nivel de riesgo dado, o minimizar el riesgo para un rendimiento esperado. Esta idea fue propuesta por Harry Markowitz en 1952, quien mostró cómo diversificar adecuadamente las inversiones puede reducir el riesgo total de un portafolio sin sacrificar el rendimiento.
# 
# En términos simples, la frontera eficiente es como un "mapa" que te guía a la mejor relación entre riesgo y ganancia. Al elegir los activos correctos y combinarlos de manera eficiente, puedes obtener el máximo rendimiento posible sin asumir un riesgo excesivo. Además, el riesgo total del portafolio no es solo la suma de los riesgos de cada activo, sino que también depende de cómo se comportan juntos, es decir, de la covarianza entre los activos.
# 
# La importancia de la frontera eficiente radica en que te ayuda a crear un portafolio óptimo, balanceando riesgo y rentabilidad de manera informada y estratégica.
# 
# En resumen, la frontera eficiente ayuda a encontrar la mejor relación entre riesgo y rentabilidad, utilizando la diversificación para reducir el riesgo total del portafolio. Esto convierte a la optimización de portafolios en una herramienta clave para los inversionistas que buscan maximizar el rendimiento mientras controlan el riesgo.
# 
# 
# **Propuesta 2:**
# 
# **Efecto de la Correlación y Diversificación**
# 
# La diversificación y la correlación son dos conceptos clave para gestionar el riesgo y optimizar los rendimientos en un portafolio de inversión. Ambos están muy relacionados y, cuando se usan correctamente, permiten reducir el riesgo y maximizar las ganancias.
# 
# **Diversificación:**
# 
# La diversificación es una estrategia en la que se distribuye el dinero entre diferentes tipos de activos (acciones, bonos, bienes raíces, etc.) para minimizar el riesgo de perder todo el dinero en caso de que un activo tenga mal rendimiento. Al tener inversiones en distintos sectores o mercados, si uno pierde valor, el rendimiento de otros activos puede compensarlo.
# 
# - ***Ejemplo:*** If you only invest in technology stocks and the technology sector falls, your entire portfolio would lose value. But if you also invest in other assets like bonds or stocks from sectors like energy or healthcare, it's less likely that all assets will fall at the same time, which reduces overall risk.
# 
# La diversificación ayuda a reducir el riesgo idiosincrático, es decir, el riesgo específico de una empresa o sector. The key is to choose assets that don't behave in the same way, so that if one goes down, the other doesn't have to.
# 
# **Correlación:**
# 
# La correlación mide cómo se comportan dos activos en relación entre sí. Existen tres tipos de correlación:
# 
# - ***Correlación positiva (+1):*** Cuando un activo sube, el otro también sube. Los activos se mueven en la misma dirección.
# **Ejemplo:** Dos acciones tecnológicas que suben o bajan juntas.
# 
# - ***Correlación negativa (-1):*** Cuando un activo sube, el otro baja. Esto es útil para la diversificación, ya que reduce el riesgo total al equilibrar los movimientos.
# **Ejemplo:** Si las acciones caen, los bonos pueden subir, ya que los inversores buscan refugio en los bonos seguros.
# 
# - ***Correlación cero (0):*** Los activos no tienen relación entre sí, es decir, sus movimientos no afectan al otro.
# **Ejemplo:** El precio del oro y las acciones de una empresa tecnológica pueden no estar relacionados.
# 
# ***Relación entre Diversificación y Correlación:***
# 
# La diversificación es más efectiva cuando se seleccionan activos con baja correlación. Si todos los activos se comportan de la misma forma (correlación positiva alta), no estarás reduciendo el riesgo. Por el contrario, si eliges activos con correlación negativa o baja, el riesgo total del portafolio se reduce, ya que los rendimientos de un activo pueden compensar las pérdidas de otro.
# 
# Markowitz (1952) fue uno de los primeros en mostrar que la diversificación se logra mejor cuando los activos tienen bajas covarianzas entre sí. Según el, es importante evitar invertir en activos con altas covarianzas y, en su lugar, diversificar a través de sectores diferentes, ya que los activos de distintos sectores tienden a tener menores covarianzas que aquellos dentro del mismo sector. This makes the portfolio more resistant to market fluctuations.
# 
# These tools help build a balanced portfolio that maximizes profit opportunities and minimizes overall risk, ensuring greater stability against market fluctuations.
# 
# 
# **Propuesta 3:Análisis de rentabilidad y riesgo***
# 
# El análisis de rentabilidad y riesgo es fundamental en la toma de decisiones de inversión. Permite a los inversionistas evaluar las posibles ganancias de una inversión en relación con el riesgo que están dispuestos a asumir.
# 
# **Rentabilidad:**
# 
# La rentabilidad mide el rendimiento de una inversión durante un periodo de tiempo. Se calcula como la diferencia entre el valor final y el valor inicial de la inversión, expresada como un porcentaje. Existen dos formas de medirla:
# 
# - ***Rentabilidad Absoluta:*** Simplemente calcula la ganancia o pérdida en relación con la inversión inicial.
# 
# - ***Rentabilidad Annualizada (CAGR):*** Permite comparar inversiones de diferente duración al calcular el rendimiento promedio anual.
# 
# Las acciones suelen tener una rentabilidad más alta, pero también más volátil, mientras que los bonos ofrecen una rentabilidad más baja, pero con menos riesgo.
# 
# **Riesgo:**
# 
# El riesgo mide la incertidumbre sobre los rendimientos futuros. El riesgo puede ser de dos tipos:
# 
# - ***Riesgo Sistemático (de mercado):*** Es el riesgo que afecta a todo el mercado, como cambios en la economía o políticas gubernamentales. This type of risk cannot be eliminated through diversification.
# 
# - ***Riesgo No Sistemático (específico):*** Es el riesgo asociado con un activo específico, como una empresa. This risk can be reduced by diversifying the portfolio.
# 
# **El riesgo se mide con:**
# 
# - ***Volatilidad (Desviación estándar):*** Indica cuánto fluctúa el precio o rendimiento de un activo. The higher the volatility, the higher the risk.
# 
# - ***Beta (β):*** Mide la sensibilidad de un activo respecto al mercado. A high beta means the asset is more volatile than the market.
# 
# **En resumen,** el análisis de rentabilidad y riesgo permite a los inversionistas tomar decisiones informadas, balanceando los rendimientos esperados con los riesgos involucrados. La diversificación y la frontera eficiente son herramientas fundamentales para crear un portafolio equilibrado que maximice las ganancias sin asumir riesgos excesivos.
# 
# ''')
# elif Tema_seleccionado=='Selección de la propuesta':
#     st.markdown('''**Selección de la propuesta**
# 
#     ***Diversificación y correlación**
# 
#  Elegimos la propuesta de Diversificación y Correlación porque nos permite analizar cómo combinar diferentes activos para reducir el riesgo total del portafolio. Utilizaremos Python en Google Colab para calcular las correlaciones entre los activos y evaluar cómo la diversificación mejora la estabilidad del portafolio. Con librerías como NumPy, Pandas y Matplotlib, podremos analizar de manera eficiente las relaciones entre los activos, calcular métricas clave como el rendimiento esperado y la volatilidad, y visualizar los resultados, lo que nos ayudará a tomar decisiones más informadas en la construcción de un portafolio equilibrado.
#     ''')
# 
# elif Tema_seleccionado=='Herramienta':
#     st.markdown('''**Herramientas de trabajo**
# - Python en google Colab
# - Github (para versionar y compartir el proyecto''')
# elif Tema_seleccionado=='Referencias':
#     st.markdown('''**Referencias**
#   -  https://hector.marinruiz.com.mx/wp-content/uploads/YMCAFCF03100414.pdf#page=14.10
#  - https://www.investopedia.com/terms/p/portfolio.asp''')
# 
# #lista de tickert inicial
# lista_tickers=['AAPL', 'MSFT']
# #multiselector
# tickers=st.multiselect('selecciona tickers', lista_tickers)

streamlit run app.py & npx localtunnel --port 8501