# -*- coding: utf-8 -*-
"""Aplicacion_portafolio pynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/blankchechi26-alt/Borradores-Portafolio/blob/main/Aplicacion_portafolio%20pynb.ipynb
"""

import streamlit as st
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

st.title('ANÁLISIS DE PORTAFOLIO DE INVERSIÓN')

st.markdown('**INTEGRANTES DEL GRUPO**')

st.markdown('Andrea Velasquez')

st.markdown('Blanca Alvarez')

Temas=['Definición','Tipos de analisis de portafolio', 'Selección de la propuesta', 'Herramienta', 'Referencias']

Tema_seleccionado=st.selectbox('selecciona un tema;', Temas)

st.write('Has seleccionado:', Tema_seleccionado)



if Tema_seleccionado=='Definición':
    st.markdown('''**ANÁLISIS DE PORTAFOLIO DE INVERSIÓN:**

Un Análisis de Portafolio de Inversión consiste en estudiar y evaluar el conjunto de activos financieros (acciones, bonos, bienes raíces, entre otros) en el que una persona o empresa ha invertido. El objetivo de este análisis es entender cómo se comportan esos activos, tanto en términos de riesgo como de rentabilidad.

**Principios elementales de inversión**.
En todo instrumento financiero de un portafolio de inversión tienen
que considerarse los siguientes elementos:

- ***Rendimiento***: Es la ganancia que se obtendría y está dada en función a la tasa y al plazo de inversión.

Es la estimación de las ganancias que se espera obtener de las inversiones a lo largo del tiempo. Este rendimiento puede variar dependiendo de las condiciones del mercado, pero es importante proyectarlo para tomar decisiones informadas.

- ***Riesgo***: Se refiere a la posibilidad de que los rendimientos no se den como se esperaba. En este contexto, se suelen usar herramientas estadísticas como la volatilidad (que mide las fluctuaciones de los precios de los activos), la varianza y la desviación estándar para cuantificar cuán impredecibles o inestables son los rendimientos.

Debe determinarse cuánto riesgo se está dispuesto a asumir.

- ***Diversificación y correlación***: Uno de los principios clave en la gestión de un portafolio es diversificar. Esto significa invertir en diferentes tipos de activos que no se muevan de manera idéntica. La correlación entre los activos muestra si sus rendimientos tienden a moverse juntos o en direcciones opuestas. Idealmente, se buscan activos con baja correlación entre sí, para reducir el riesgo total del portafolio.

Es decir, en lugar de invertir todo el capital en un solo activo (como, por ejemplo, solo en acciones de una empresa), se distribuye entre diferentes activos, clases de activos o mercados. Al hacer esto, se busca minimizar el impacto de los posibles rendimientos negativos de un activo específico.

- ***Relación riesgo-retorno***: Un análisis de portafolio también evalúa si el rendimiento que se espera obtener justifica el riesgo que se asume. Es decir, busca encontrar un balance entre obtener buenos rendimientos sin exponerse a un riesgo excesivo.

**En resumen**, Un portafolio de inversión es un conjunto de activos financieros que se combinan para generar rendimientos con un nivel de riesgo controlado. La diversificación busca repartir el dinero entre diferentes activos para reducir riesgos, mientras que la correlación mide cómo se comportan esos activos entre sí. El objetivo es equilibrar el riesgo y el retorno para optimizar las ganancias.

Es una herramienta crucial para los inversionistas que buscan maximizar su rentabilidad y minimizar los riesgos asociados con sus decisiones financieras.''')
elif Tema_seleccionado=='Tipos de analisis de portafolio':
    st.markdown('''**TIPOS DE ANALISIS DE PORTAFOLIO:**
***Presentamos las siguientes propuestas:***

**Propuesta 1:**

**Optimización de portafolio: Frontera eficiente**

La frontera eficiente es un concepto clave en la optimización de portafolios de inversión. Se refiere a la combinación ideal de activos que te permite maximizar el rendimiento para un nivel de riesgo dado, o minimizar el riesgo para un rendimiento esperado. Esta idea fue propuesta por Harry Markowitz en 1952, quien mostró cómo diversificar adecuadamente las inversiones puede reducir el riesgo total de un portafolio sin sacrificar el rendimiento.

En términos simples, la frontera eficiente es como un "mapa" que te guía a la mejor relación entre riesgo y ganancia. Al elegir los activos correctos y combinarlos de manera eficiente, puedes obtener el máximo rendimiento posible sin asumir un riesgo excesivo. Además, el riesgo total del portafolio no es solo la suma de los riesgos de cada activo, sino que también depende de cómo se comportan juntos, es decir, de la covarianza entre los activos.

La importancia de la frontera eficiente radica en que te ayuda a crear un portafolio óptimo, balanceando riesgo y rentabilidad de manera informada y estratégica.

En resumen, la frontera eficiente ayuda a encontrar la mejor relación entre riesgo y rentabilidad, utilizando la diversificación para reducir el riesgo total del portafolio. Esto convierte a la optimización de portafolios en una herramienta clave para los inversionistas que buscan maximizar el rendimiento mientras controlan el riesgo.


**Propuesta 2:**

**Efecto de la Correlación y Diversificación**

La diversificación y la correlación son dos conceptos clave para gestionar el riesgo y optimizar los rendimientos en un portafolio de inversión. Ambos están muy relacionados y, cuando se usan correctamente, permiten reducir el riesgo y maximizar las ganancias.

**Diversificación:**

La diversificación es una estrategia en la que se distribuye el dinero entre diferentes tipos de activos (acciones, bonos, bienes raíces, etc.) para minimizar el riesgo de perder todo el dinero en caso de que un activo tenga mal rendimiento. Al tener inversiones en distintos sectores o mercados, si uno pierde valor, el rendimiento de otros activos puede compensarlo.

- ***Ejemplo:*** Si solo inviertes en acciones de tecnología y el sector tecnológico cae, todo tu portafolio perdería valor. Pero si también inviertes en otros activos como bonos o acciones de sectores como energía o salud, es menos probable que todos los activos caigan al mismo tiempo, lo que reduce el riesgo global.

La diversificación ayuda a reducir el riesgo idiosincrático, es decir, el riesgo específico de una empresa o sector. La clave es elegir activos que no se comporten de la misma forma, para que si uno baja, el otro no tenga que hacerlo.

**Correlación:**

La correlación mide cómo se comportan dos activos en relación entre sí. Existen tres tipos de correlación:

- ***Correlación positiva (+1):*** Cuando un activo sube, el otro también sube. Los activos se mueven en la misma dirección.
**Ejemplo:** Dos acciones tecnológicas que suben o bajan juntas.

- ***Correlación negativa (-1):*** Cuando un activo sube, el otro baja. Esto es útil para la diversificación, ya que reduce el riesgo total al equilibrar los movimientos.
**Ejemplo:** Si las acciones caen, los bonos pueden subir, ya que los inversores buscan refugio en los bonos seguros.

- ***Correlación cero (0):*** Los activos no tienen relación entre sí, es decir, sus movimientos no afectan al otro.
**Ejemplo:** El precio del oro y las acciones de una empresa tecnológica pueden no estar relacionados.

***Relación entre Diversificación y Correlación:***

La diversificación es más efectiva cuando se seleccionan activos con baja correlación. Si todos los activos se comportan de la misma forma (correlación positiva alta), no estarás reduciendo el riesgo. Por el contrario, si eliges activos con correlación negativa o baja, el riesgo total del portafolio se reduce, ya que los rendimientos de un activo pueden compensar las pérdidas de otro.

Markowitz (1952) fue uno de los primeros en mostrar que la diversificación se logra mejor cuando los activos tienen bajas covarianzas entre sí. Según el, es importante evitar invertir en activos con altas covarianzas y, en su lugar, diversificar a través de sectores diferentes, ya que los activos de distintos sectores tienden a tener menores covarianzas que aquellos dentro del mismo sector. Esto hace que el portafolio sea más resistente a fluctuaciones del mercado.

Estas herramientas ayudan a construir un portafolio equilibrado que maximiza las oportunidades de ganancia y minimiza el riesgo total, asegurando una mayor estabilidad frente a fluctuaciones del mercado.


**Propuesta 3:Análisis de rentabilidad y riesgo***

El análisis de rentabilidad y riesgo es fundamental en la toma de decisiones de inversión. Permite a los inversionistas evaluar las posibles ganancias de una inversión en relación con el riesgo que están dispuestos a asumir.

**Rentabilidad:**

La rentabilidad mide el rendimiento de una inversión durante un periodo de tiempo. Se calcula como la diferencia entre el valor final y el valor inicial de la inversión, expresada como un porcentaje. Existen dos formas de medirla:

- ***Rentabilidad Absoluta:*** Simplemente calcula la ganancia o pérdida en relación con la inversión inicial.

- ***Rentabilidad Annualizada (CAGR):*** Permite comparar inversiones de diferente duración al calcular el rendimiento promedio anual.

Las acciones suelen tener una rentabilidad más alta, pero también más volátil, mientras que los bonos ofrecen una rentabilidad más baja, pero con menos riesgo.

**Riesgo:**

El riesgo mide la incertidumbre sobre los rendimientos futuros. El riesgo puede ser de dos tipos:

- ***Riesgo Sistemático (de mercado):*** Es el riesgo que afecta a todo el mercado, como cambios en la economía o políticas gubernamentales. Este tipo de riesgo no se puede eliminar mediante diversificación.

- ***Riesgo No Sistemático (específico):*** Es el riesgo asociado con un activo específico, como una empresa. Este riesgo puede reducirse al diversificar el portafolio.

**El riesgo se mide con:**

- ***Volatilidad (Desviación estándar):*** Indica cuánto fluctúa el precio o rendimiento de un activo. Cuanto mayor es la volatilidad, mayor es el riesgo.

- ***Beta (β):*** Mide la sensibilidad de un activo respecto al mercado. Un beta alto significa que el activo es más volátil que el mercado.

**En resumen,** el análisis de rentabilidad y riesgo permite a los inversionistas tomar decisiones informadas, balanceando los rendimientos esperados con los riesgos involucrados. La diversificación y la frontera eficiente son herramientas fundamentales para crear un portafolio equilibrado que maximice las ganancias sin asumir riesgos excesivos.

''')
elif Tema_seleccionado=='Selección de la propuesta':
    st.markdown('''**Selección de la propuesta**

    ***Diversificación y correlación**

 Elegimos la propuesta de Diversificación y Correlación porque nos permite analizar cómo combinar diferentes activos para reducir el riesgo total del portafolio. Utilizaremos Python en Google Colab para calcular las correlaciones entre los activos y evaluar cómo la diversificación mejora la estabilidad del portafolio. Con librerías como NumPy, Pandas y Matplotlib, podremos analizar de manera eficiente las relaciones entre los activos, calcular métricas clave como el rendimiento esperado y la volatilidad, y visualizar los resultados, lo que nos ayudará a tomar decisiones más informadas en la construcción de un portafolio equilibrado.
    ''')
elif Tema_seleccionado=='Ejemplo ticker':
     st.markdown('''**Selección de ejemplo de diversificación**
     st.title('EJEMPLO ACCION)
st.subheader('Ejemplo práctico de diversificación con dos acciones')

st.markdown("""
Este ejemplo muestra cómo la **diversificación** reduce el riesgo al combinar activos de distintos sectores.
Usaremos las acciones de **Apple (AAPL)** y **Coca-Cola (KO)**.
""")

# -------------------------------
# Selección de acciones
# -------------------------------
tickers = ['AAPL', 'KO']
st.write("**Acciones seleccionadas:**", tickers)

# -------------------------------
# Descarga de datos desde Yahoo Finance
# -------------------------------
# Removed the try...except block to allow the error to propagate if yf.download fails.
data = yf.download(tickers, start='2022-01-01', end='2025-01-01')
st.subheader("📊 Precios históricos ajustados")
st.dataframe(data.tail())


# -------------------------------
# Cálculo de rendimientos
# -------------------------------
# Select the 'Close' price from the MultiIndex data
close_prices = data['Close']
returns = close_prices.pct_change().dropna()

st.subheader("📈 Estadísticas de rentabilidad diaria")
st.write(returns.describe())

# -------------------------------
# Gráfico de evolución de precios
# -------------------------------
st.subheader("📉 Evolución del precio de las acciones")
fig, ax = plt.subplots()
close_prices.plot(ax=ax)
ax.set_xlabel("Fecha")
ax.set_ylabel("Precio ajustado (USD)")
st.pyplot(fig)

# -------------------------------
# Gráfico de dispersión (correlación)
# -------------------------------
st.subheader("🔗 Relación entre los rendimientos (correlación)")
fig2, ax2 = plt.subplots()
ax2.scatter(returns['AAPL'], returns['KO'], alpha=0.6)
ax2.set_xlabel('Rendimiento diario de Apple (AAPL)')
ax2.set_ylabel('Rendimiento diario de Coca-Cola (KO)')
ax2.set_title('Diversificación entre Apple y Coca-Cola')
st.pyplot(fig2)

# -------------------------------
# Matriz de correlación
# -------------------------------
st.subheader("📊 Matriz de correlación")
correlacion = returns.corr()
st.write(correlacion)

# -------------------------------
# Interpretación
# -------------------------------
st.markdown("""
### 💡 Interpretación
- Si la **correlación** entre AAPL y KO es **baja o negativa**, significa que las acciones no se mueven igual:
  cuando una baja, la otra puede subir o mantenerse estable.
- Esto **reduce el riesgo total del portafolio** y demuestra la utilidad de la **diversificación**.

**Conclusión:** combinar activos de sectores distintos (tecnología y consumo) genera un portafolio más estable frente a la volatilidad del mercado.
""")

elif Tema_seleccionado=='Herramienta':
    st.markdown('''**Herramientas de trabajo**
- Python en google Colab
- Github (para versionar y compartir el proyecto''')
elif Tema_seleccionado=='Referencias':
    st.markdown('''**Referencias**
  -  https://hector.marinruiz.com.mx/wp-content/uploads/YMCAFCF03100414.pdf#page=14.10
