# -*- coding: utf-8 -*-
"""Borrador 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cn1ZFTxXnVTVFMPaEH7ao5FuZEvTmRpH
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

st.set_page_config(page_title="Portfolio Analyzer", layout="wide")

# --- LISTA DE 500 ACCIONES (TOP USA) ---
tickers_usa = pd.read_csv(
    "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/data/constituents.csv"
)["Symbol"].tolist()

# --- SIDEBAR ---
st.sidebar.header("Parámetros de análisis")

tickers = st.sidebar.multiselect(
    "Selecciona una o varias acciones",
    options=tickers_usa,
    default=["AAPL"]
)

start = st.sidebar.date_input("Fecha inicial", pd.to_datetime("2020-01-01"))
end = st.sidebar.date_input("Fecha final", pd.to_datetime("today"))

initial_investment = st.sidebar.number_input(
    "Inversión inicial (USD)",
    min_value=100.0,
    value=10000.0,
    step=100.0
)

freq = st.sidebar.selectbox(
    "Frecuencia temporal",
    ["1d", "1wk", "1mo"]
)

if len(tickers) == 0:
    st.warning("Selecciona al menos una acción.")
    st.stop()

# --- DESCARGA DE DATOS ---
data = yf.download(tickers, start=start, end=end, interval=freq)["Adj Close"]

if isinstance(data, pd.Series):
    data = data.to_frame()

returns = data.pct_change().dropna()
cum_returns = (1 + returns).cumprod()

# --- MÉTRICAS ---
vol = returns.std() * np.sqrt(252)
mean_ret = returns.mean() * 252
sharpe = (mean_ret - 0.02) / vol  # suposición: 2% risk-free rate

weights = np.ones(len(tickers)) / len(tickers)
portfolio_daily = (returns @ weights)
portfolio_value = initial_investment * (1 + portfolio_daily).cumprod()

# --- BENCHMARK ---
bench = yf.download("SPY", start=start, end=end, interval=freq)["Adj Close"]
bench_ret = bench.pct_change().dropna()
bench_cum = (1 + bench_ret).cumprod()

st.title("📊 Portfolio Analyzer")

# --- GRÁFICOS ---
col1, col2 = st.columns(2)

with col1:
    st.subheader("Serie de precios")
    fig, ax = plt.subplots()
    data.plot(ax=ax)
    st.pyplot(fig)

with col2:
    st.subheader("Retornos acumulados")
    fig, ax = plt.subplots()
    cum_returns.plot(ax=ax)
    bench_cum.rename("SPY").plot(ax=ax, linestyle="--")
    ax.set_title("Retorno acumulado vs SPY")
    st.pyplot(fig)

st.subheader("Valor del portafolio")
fig, ax = plt.subplots()
ax.plot(portfolio_value, label="Portafolio")
ax.set_title("Evolución del valor")
ax.legend()
st.pyplot(fig)

# --- RIESGO - RETORNO ---
st.subheader("Diagrama riesgo-retorno")
fig, ax = plt.subplots()
ax.scatter(vol, mean_ret)
for t in tickers:
    ax.annotate(t, (vol[t], mean_ret[t]))
ax.set_xlabel("Volatilidad anualizada")
ax.set_ylabel("Retorno anualizado")
st.pyplot(fig)

# --- HEATMAP CORRELACIONES ---
st.subheader("Correlaciones")
corr = returns.corr()
fig, ax = plt.subplots()
im = ax.imshow(corr, cmap="coolwarm")
plt.colorbar(im)
ax.set_xticks(range(len(corr.columns)))
ax.set_yticks(range(len(corr.index)))
ax.set_xticklabels(corr.columns, rotation=90)
ax.set_yticklabels(corr.index)
st.pyplot(fig)

# --- TABLA METRICAS ---
st.subheader("Métricas por activo")
metrics = pd.DataFrame({
    "Retorno anual": mean_ret,
    "Volatilidad anual": vol,
    "Sharpe Ratio": sharpe
})
st.dataframe(metrics)