# -*- coding: utf-8 -*-
"""borrador 10 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14swWnR-myB_cZGdpoqztzbBnkfCkDP7J
"""

# -*- coding: utf-8 -*-
"""Aplicación interactiva de análisis de portafolio con Streamlit y Yahoo Finance"""

import streamlit as st
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

# -----------------------------------------------------------
# TÍTULO E INTRODUCCIÓN
# -----------------------------------------------------------
st.title("📈 ANÁLISIS DE PORTAFOLIO DE INVERSIÓN")
st.markdown("""
Explora cómo la **diversificación** reduce el riesgo al combinar activos de distintos sectores.
Selecciona dos acciones, visualiza su comportamiento y analiza la relación entre riesgo y rentabilidad.
""")

# -----------------------------------------------------------
# MENÚ LATERAL
# -----------------------------------------------------------
st.sidebar.header("⚙️ Controles de análisis")

# Selección de acciones (puedes elegir cualquiera de Yahoo Finance)
ticker1 = st.sidebar.text_input("Primera acción (ejemplo: AAPL)", "AAPL")
ticker2 = st.sidebar.text_input("Segunda acción (ejemplo: KO)", "KO")

# Fechas de análisis
fecha_inicio = st.sidebar.date_input("Fecha de inicio", pd.to_datetime("2022-01-01"))
fecha_fin = st.sidebar.date_input("Fecha final", pd.to_datetime("2025-01-01"))

# Botón para ejecutar el análisis
if st.sidebar.button("Ejecutar análisis"):

    tickers = [ticker1.upper(), ticker2.upper()]
    st.subheader(f"📊 Acciones seleccionadas: {tickers}")

    # -----------------------------------------------------------
    # DESCARGA DE DATOS
    # -----------------------------------------------------------
    try:
        data = yf.download(tickers, start=fecha_inicio, end=fecha_fin)['Adj Close']
        st.write("Datos descargados correctamente ✅")
    except Exception as e:
        st.error(f"Error al descargar datos: {e}")
        st.stop()

    st.dataframe(data.tail())

    # -----------------------------------------------------------
    # CÁLCULO DE RENDIMIENTOS
    # -----------------------------------------------------------
    returns = data.pct_change().dropna()
    st.subheader("📈 Estadísticas de rentabilidad diaria")
    st.write(returns.describe())

    # -----------------------------------------------------------
    # MENÚ DE VISUALIZACIÓN
    # -----------------------------------------------------------
    opcion_vista = st.selectbox(
        "Selecciona el tipo de gráfico a mostrar:",
        ("Evolución de precios", "Relación de rendimientos", "Matriz de correlación")
    )

    # -----------------------------------------------------------
    # GRÁFICOS
    # -----------------------------------------------------------
    if opcion_vista == "Evolución de precios":
        st.subheader("📉 Evolución del precio de las acciones")
        fig, ax = plt.subplots()
        data.plot(ax=ax)
        ax.set_xlabel("Fecha")
        ax.set_ylabel("Precio ajustado (USD)")
        st.pyplot(fig)

    elif opcion_vista == "Relación de rendimientos":
        st.subheader("🔗 Relación entre los rendimientos (correlación)")
        fig2, ax2 = plt.subplots()
        ax2.scatter(returns[ticker1.upper()], returns[ticker2.upper()], alpha=0.6)
        ax2.set_xlabel(f"Rendimiento diario de {ticker1.upper()}")
        ax2.set_ylabel(f"Rendimiento diario de {ticker2.upper()}")
        ax2.set_title(f"Diversificación: {ticker1.upper()} vs {ticker2.upper()}")
        st.pyplot(fig2)

    elif opcion_vista == "Matriz de correlación":
        st.subheader("📊 Matriz de correlación")
        correlacion = returns.corr()
        st.write(correlacion)

    # -----------------------------------------------------------
    # INTERPRETACIÓN
    # -----------------------------------------------------------
    st.markdown("""
    ### 💡 Interpretación
    - Si la **correlación** entre las dos acciones es **baja o negativa**, significa que no se mueven igual:
      cuando una baja, la otra puede subir o mantenerse estable.
    - Esto **reduce el riesgo total del portafolio** y demuestra la utilidad de la **diversificación**.

    **Conclusión:**
    Combinar activos de sectores distintos genera un portafolio más estable frente a la volatilidad del mercado.
    """)

else:
    st.info("👈 Selecciona las acciones y presiona **Ejecutar análisis** para comenzar.")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit