# -*- coding: utf-8 -*-
"""Borrador 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cn1ZFTxXnVTVFMPaEH7ao5FuZEvTmRpH
"""

import streamlit as st
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import numpy as np

# Configuración de la página
st.set_page_config(
    page_title="Análisis de Acciones",
    page_icon="📈",
    layout="wide"
)

# Título de la aplicación
st.title("📈 Demo: Análisis de Acciones")
st.markdown("---")

# Sidebar para controles
st.sidebar.header("Configuración")

# Selección de tickers por defecto
default_tickers = ['AAPL', 'GOOGL', 'MSFT', 'TSLA', 'AMZN']

tickers_input = st.sidebar.text_input(
    "Símbolos de acciones (separados por coma):",
    value=", ".join(default_tickers)
)

# Procesar los tickers
tickers = [ticker.strip().upper() for ticker in tickers_input.split(',') if ticker.strip()]

# Selector de fecha
col1, col2 = st.sidebar.columns(2)
with col1:
    start_date = st.date_input(
        "Fecha de inicio:",
        value=datetime.now() - timedelta(days=365)
    )
with col2:
    end_date = st.date_input(
        "Fecha de fin:",
        value=datetime.now()
    )

# Selector de intervalo
interval = st.sidebar.selectbox(
    "Intervalo:",
    options=["1d", "1wk", "1mo"],
    index=0
)

# Función segura para descargar datos
@st.cache_data(ttl=3600)  # Cache por 1 hora
def download_stock_data(tickers, start_date, end_date, interval):
    """
    Descarga datos de acciones de manera segura
    """
    try:
        data = yf.download(
            tickers=tickers,
            start=start_date,
            end=end_date,
            interval=interval,
            progress=False
        )

        # Verificar si se descargaron datos
        if data.empty:
            st.error("No se pudieron descargar datos. Verifica los símbolos y fechas.")
            return None

        return data

    except Exception as e:
        st.error(f"Error al descargar datos: {str(e)}")
        return None

# Botón para cargar datos
if st.sidebar.button("Cargar Datos", type="primary"):
    with st.spinner("Descargando datos..."):
        stock_data = download_stock_data(tickers, start_date, end_date, interval)
else:
    # Datos por defecto
    stock_data = download_stock_data(default_tickers, start_date, end_date, interval)

# Mostrar datos si están disponibles
if stock_data is not None:

    # Pestañas para diferentes análisis
    tab1, tab2, tab3, tab4 = st.tabs(["📊 Precios", "📈 Rendimientos", "🔍 Correlaciones", "📋 Datos"])

    with tab1:
        st.subheader("Precios de Cierre Ajustados")

        # Obtener precios de cierre ajustados de manera segura
        if 'Adj Close' in stock_data.columns:
            prices = stock_data['Adj Close']
        else:
            # Si no hay columna multi-nivel, usar directamente
            prices = stock_data

        # Limpiar datos nulos
        prices = prices.dropna()

        if not prices.empty:
            # Normalizar precios para comparación (base 100)
            normalized_prices = (prices / prices.iloc[0]) * 100

            # Gráfico de precios
            fig, ax = plt.subplots(figsize=(12, 6))
            for column in normalized_prices.columns:
                ax.plot(normalized_prices.index, normalized_prices[column], label=column, linewidth=2)

            ax.set_title('Evolución de Precios (Normalizado)', fontsize=16, fontweight='bold')
            ax.set_xlabel('Fecha')
            ax.set_ylabel('Precio (Base 100)')
            ax.legend()
            ax.grid(True, alpha=0.3)
            plt.xticks(rotation=45)
            st.pyplot(fig)

            # Estadísticas rápidas
            st.subheader("Estadísticas de Precios")
            col1, col2, col3, col4 = st.columns(4)

            latest_prices = prices.iloc[-1]
            price_changes = ((prices.iloc[-1] - prices.iloc[0]) / prices.iloc[0]) * 100

            for i, ticker in enumerate(prices.columns):
                with [col1, col2, col3, col4][i % 4]:
                    st.metric(
                        label=ticker,
                        value=f"${latest_prices[ticker]:.2f}",
                        delta=f"{price_changes[ticker]:.2f}%"
                    )

    with tab2:
        st.subheader("Rendimientos Diarios")

        if 'Adj Close' in stock_data.columns:
            prices = stock_data['Adj Close'].dropna()
        else:
            prices = stock_data.dropna()

        if not prices.empty:
            # Calcular rendimientos
            returns = prices.pct_change().dropna()

            # Gráfico de rendimientos
            fig, ax = plt.subplots(figsize=(12, 6))
            returns.plot(ax=ax)
            ax.set_title('Rendimientos Diarios', fontsize=16, fontweight='bold')
            ax.set_xlabel('Fecha')
            ax.set_ylabel('Rendimiento')
            ax.legend()
            ax.grid(True, alpha=0.3)
            plt.xticks(rotation=45)
            st.pyplot(fig)

            # Distribución de rendimientos
            st.subheader("Distribución de Rendimientos")
            fig, axes = plt.subplots(2, 2, figsize=(12, 10))
            axes = axes.flatten()

            for i, ticker in enumerate(returns.columns[:4]):
                axes[i].hist(returns[ticker].dropna(), bins=50, alpha=0.7, edgecolor='black')
                axes[i].set_title(f'Distribución - {ticker}')
                axes[i].set_xlabel('Rendimiento')
                axes[i].set_ylabel('Frecuencia')
                axes[i].grid(True, alpha=0.3)

            plt.tight_layout()
            st.pyplot(fig)

    with tab3:
        st.subheader("Matriz de Correlación")

        if 'Adj Close' in stock_data.columns:
            prices = stock_data['Adj Close'].dropna()
        else:
            prices = stock_data.dropna()

        if not prices.empty:
            returns = prices.pct_change().dropna()
            correlation_matrix = returns.corr()

            # Heatmap de correlaciones
            fig, ax = plt.subplots(figsize=(10, 8))
            sns.heatmap(
                correlation_matrix,
                annot=True,
                cmap='coolwarm',
                center=0,
                square=True,
                ax=ax
            )
            ax.set_title('Matriz de Correlación entre Acciones', fontsize=16, fontweight='bold')
            st.pyplot(fig)

    with tab4:
        st.subheader("Datos en Tiempo Real")

        if 'Adj Close' in stock_data.columns:
            display_data = stock_data['Adj Close']
        else:
            display_data = stock_data

        # Mostrar últimas 10 filas
        st.dataframe(display_data.tail(10), use_container_width=True)

        # Descargar datos
        csv = display_data.to_csv()
        st.download_button(
            label="Descargar CSV",
            data=csv,
            file_name=f"stock_data_{datetime.now().strftime('%Y%m%d')}.csv",
            mime="text/csv"
        )

else:
    st.warning("""
    ⚠️ No se pudieron cargar los datos. Algunas posibles soluciones:

    1. **Verifica los símbolos**: Asegúrate de que los símbolos de acciones sean correctos
    2. **Revisa las fechas**: Las fechas deben ser válidas y en orden cronológico
    3. **Problemas de conexión**: Verifica tu conexión a internet
    4. **Símbolos populares**: Prueba con AAPL, GOOGL, MSFT, TSLA

    Ejemplo de formato correcto: `AAPL, GOOGL, MSFT`
    """)

# Información adicional en el sidebar
st.sidebar.markdown("---")
st.sidebar.info("""
**💡 Tips:**
- Usa símbolos válidos de Yahoo Finance
- Intervalos disponibles: 1d, 1wk, 1mo
- Los datos se actualizan automáticamente
""")

# Footer
st.markdown("---")
st.markdown(
    "📊 *Demo creado para análisis de datos financieros* • "
    "Usa los controles laterales para personalizar tu análisis"
)