# -*- coding: utf-8 -*-
"""Diversificacion .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKUdK2d2_YB7f27nMz3M3XNio-fxOM_s
"""

# Commented out IPython magic to ensure Python compatibility.
# # -*- coding: utf-8 -*-
# """Aplicación completa de Análisis de Portafolio de Inversión (Colab + Streamlit)"""
# 
# # -----------------------------------------------------------
# # INSTALACIÓN DE DEPENDENCIAS (solo la primera vez)
# # -----------------------------------------------------------
# !pip install streamlit yfinance pandas matplotlib --quiet
# 
# # -----------------------------------------------------------
# # CÓDIGO DE LA APLICACIÓN STREAMLIT
# # -----------------------------------------------------------
# %%writefile app_portafolio.py
# import streamlit as st
# import pandas as pd
# import yfinance as yf
# import matplotlib.pyplot as plt
# 
# # -----------------------------------------------------------
# # CONFIGURACIÓN DE LA PÁGINA
# # -----------------------------------------------------------
# st.set_page_config(page_title="Análisis de Portafolio de Inversión", page_icon="📈", layout="centered")
# 
# # -----------------------------------------------------------
# # PORTADA
# # -----------------------------------------------------------
# st.title("📊 ANÁLISIS DE PORTAFOLIO DE INVERSIÓN")
# st.markdown("""
# **Integrantes del grupo:**
# - Andrea Velásquez
# - Blanca Álvarez
# 
# **Carrera:** Ingeniería Financiera
# **Institución:** [Tu universidad aquí]
# ---
# """)
# 
# # -----------------------------------------------------------
# # MENÚ LATERAL PRINCIPAL
# # -----------------------------------------------------------
# menu = st.sidebar.radio(
#     "Navegación",
#     [
#         "🏠 Introducción",
#         "📘 Marco Teórico",
#         "🧩 Selección de Propuesta",
#         "🧰 Herramientas de Trabajo",
#         "📈 Análisis Práctico (Tickers)",
#         "📚 Referencias"
#     ]
# )
# 
# # -----------------------------------------------------------
# # 1️⃣ INTRODUCCIÓN
# # -----------------------------------------------------------
# if menu == "🏠 Introducción":
#     st.header("Definición general")
#     st.markdown("""
#     Un **análisis de portafolio de inversión** estudia y evalúa el conjunto de activos financieros
#     (acciones, bonos, bienes raíces, entre otros) en el que una persona o empresa ha invertido.
#     Su objetivo es comprender el comportamiento de esos activos en términos de **riesgo y rentabilidad**.
# 
#     En un portafolio deben considerarse los siguientes elementos:
# 
#     - **Rendimiento:** Ganancia obtenida en función de la tasa y el plazo de inversión.
#     - **Riesgo:** Posibilidad de que los rendimientos no sean los esperados.
#     - **Diversificación:** Invertir en distintos tipos de activos para reducir el riesgo total.
#     - **Correlación:** Mide si los activos se mueven juntos o en direcciones opuestas.
#     - **Relación riesgo–retorno:** Evalúa si el rendimiento esperado compensa el riesgo asumido.
# 
#     En resumen, el análisis de portafolio busca **equilibrar riesgo y rendimiento** mediante la diversificación inteligente.
#     """)
# 
# # -----------------------------------------------------------
# # 2️⃣ MARCO TEÓRICO
# # -----------------------------------------------------------
# elif menu == "📘 Marco Teórico":
#     st.header("Tipos de Análisis de Portafolio")
# 
#     st.markdown("""
#     **1. Optimización del Portafolio (Frontera Eficiente)**
#     Propone combinaciones óptimas de activos para maximizar rendimiento o minimizar riesgo.
#     La frontera eficiente, introducida por *Harry Markowitz (1952)*, define el punto ideal donde se obtiene
#     la mejor relación entre riesgo y ganancia esperada.
# 
#     **2. Correlación y Diversificación**
#     - La **correlación positiva** (+1) indica que los activos se mueven juntos.
#     - La **correlación negativa** (-1) significa que cuando uno sube, el otro baja.
#     - La **correlación cero** muestra que no hay relación entre ellos.
#     La clave es combinar activos con baja correlación para reducir el riesgo global.
# 
#     **3. Rentabilidad y Riesgo**
#     - *Rentabilidad Absoluta*: Ganancia total respecto a la inversión inicial.
#     - *Rentabilidad Anualizada (CAGR)*: Promedio anual del rendimiento.
#     - *Riesgo Sistemático*: Afecta a todo el mercado (ej. inflación, recesión).
#     - *Riesgo No Sistemático*: Específico de una empresa o activo, reducible por diversificación.
#     """)
# 
# # -----------------------------------------------------------
# # 3️⃣ SELECCIÓN DE LA PROPUESTA
# # -----------------------------------------------------------
# elif menu == "🧩 Selección de Propuesta":
#     st.header("Propuesta seleccionada: Diversificación y Correlación")
#     st.markdown("""
#     Elegimos esta propuesta porque permite analizar cómo **combinar diferentes activos** para reducir el riesgo total del portafolio.
#     Utilizaremos **Python** (en Google Colab) para calcular las correlaciones entre los activos y evaluar cómo la diversificación mejora la estabilidad.
# 
#     Con librerías como **NumPy**, **Pandas** y **Matplotlib**, analizaremos las relaciones entre los activos,
#     calcularemos métricas clave (rendimiento, volatilidad) y visualizaremos los resultados
#     para apoyar decisiones financieras informadas.
#     """)
# 
# # -----------------------------------------------------------
# # 4️⃣ HERRAMIENTAS DE TRABAJO
# # -----------------------------------------------------------
# elif menu == "🧰 Herramientas de Trabajo":
#     st.header("Herramientas Utilizadas")
#     st.markdown("""
#     - 🐍 **Python** en Google Colab
#     - 📦 **Pandas, NumPy, Matplotlib** para análisis y visualización
#     - 🌐 **Yahoo Finance (yfinance)** para descargar datos reales de mercado
#     - 💻 **GitHub** para versionar y compartir el proyecto
#     """)
# 
# # -----------------------------------------------------------
# # 5️⃣ ANÁLISIS PRÁCTICO (INTERACTIVO)
# # -----------------------------------------------------------
# elif menu == "📈 Análisis Práctico (Tickers)":
#     st.header("Análisis de Portafolio con Acciones Reales")
# 
#     st.markdown("Explora cómo la **diversificación** reduce el riesgo combinando acciones de diferentes sectores.")
# 
#     ticker1 = st.text_input("Primera acción (ejemplo: AAPL)", "AAPL")
#     ticker2 = st.text_input("Segunda acción (ejemplo: KO)", "KO")
#     fecha_inicio = st.date_input("Fecha de inicio", pd.to_datetime("2022-01-01"))
#     fecha_fin = st.date_input("Fecha final", pd.to_datetime("2025-01-01"))
# 
#     if st.button("Ejecutar análisis"):
#         tickers = [ticker1.upper(), ticker2.upper()]
#         st.subheader(f"📊 Acciones seleccionadas: {tickers}")
# 
#         try:
#             data = yf.download(tickers, start=fecha_inicio, end=fecha_fin)["Adj Close"]
#             st.success("Datos descargados correctamente ✅")
#         except Exception as e:
#             st.error(f"No se pudieron descargar los datos: {e}")
#             st.stop()
# 
#         st.dataframe(data.tail())
# 
#         returns = data.pct_change().dropna()
#         st.subheader("📈 Estadísticas de rentabilidad diaria")
#         st.write(returns.describe())
# 
#         opcion = st.selectbox("Tipo de gráfico:", ["Evolución de precios", "Relación de rendimientos", "Matriz de correlación"])
# 
#         if opcion == "Evolución de precios":
#             fig, ax = plt.subplots(figsize=(8, 4))
#             data.plot(ax=ax)
#             ax.set_xlabel("Fecha")
#             ax.set_ylabel("Precio ajustado (USD)")
#             st.pyplot(fig)
# 
#         elif opcion == "Relación de rendimientos":
#             fig2, ax2 = plt.subplots(figsize=(5, 5))
#             ax2.scatter(returns[tickers[0]], returns[tickers[1]], alpha=0.6, color="teal")
#             ax2.set_xlabel(f"Rendimiento diario de {tickers[0]}")
#             ax2.set_ylabel(f"Rendimiento diario de {tickers[1]}")
#             ax2.set_title("Relación entre rendimientos")
#             st.pyplot(fig2)
# 
#         else:
#             correlacion = returns.corr()
#             st.subheader("📊 Matriz de correlación")
#             st.write(correlacion.style.background_gradient(cmap="coolwarm").format("{:.2f}"))
# 
#         st.markdown("""
#         ---
#         ### 💡 Interpretación
#         Una correlación baja o negativa indica que los activos **no se mueven igual**, lo cual
#         ayuda a **reducir el riesgo total** del portafolio.
#         La diversificación entre sectores distintos produce una estructura más estable frente a la volatilidad del mercado.
#         """)
# 
# # -----------------------------------------------------------
# # 6️⃣ REFERENCIAS
# # -----------------------------------------------------------
# elif menu == "📚 Referencias":
#     st.header("Referencias Bibliográficas")
#     st.markdown("""
#     - [Marín Ruiz, H. (2014). YMCAFCF03100414.pdf](https://hector.marinruiz.com.mx/wp-content/uploads/YMCAFCF03100414.pdf#page=14.10)
#     - [Investopedia – Portfolio Definition](https://www.investopedia.com/terms/p/portfolio.asp)
#     """)
# 
# # -----------------------------------------------------------
# # FIN DEL CÓDIGO
# # -----------------------------------------------------------
# 
#

!streamlit run app_portafolio.py --server.enableCORS false --server.enableXsrfProtection false