# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pnUAM-GEqM3Qe-0u-jolLb1Z-zbkily-
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

# ======================================================
# ESTILO GLOBAL
# ======================================================

st.set_page_config(page_title="Portafolio Financiero", layout="wide")

# CSS para look profesional
st.markdown("""
<style>
body { background-color: #0e1117; }
.main { background-color: #0e1117; }
h1, h2, h3, h4, h5, h6, label, .stMetric { color: #e5e5e5 !important; }
.stSelectbox div, .stDateInput, .stNumberInput label { color: #e5e5e5 !important; }
.css-10trblm, .css-1d391kg, .css-1kyxreq { color: #e5e5e5 !important; }
</style>
""", unsafe_allow_html=True)

# ======================================================
# FUNCIONES
# ======================================================

def descargar_data(tickers, start, end, freq):
    data = yf.download(tickers, start=start, end=end, interval=freq)["Adj Close"]
    return data

def calcular_retorno_portafolio(data, weights):
    retornos = data.pct_change().dropna()
    port_ret = retornos.dot(weights)
    return retornos, port_ret

def metricas_portafolio(port_ret):
    ret_acum = (1 + port_ret).prod() - 1
    vol_anual = port_ret.std() * np.sqrt(252)
    sharpe = (port_ret.mean() * 252) / (port_ret.std() * np.sqrt(252))
    return ret_acum, vol_anual, sharpe

# ======================================================
# SIDEBAR – PARÁMETROS
# ======================================================

st.sidebar.title("Parámetros")

tickers = st.sidebar.multiselect(
    "Acciones",
    ["AAPL", "MSFT", "AMZN", "GOOGL", "META", "TSLA", "NVDA"],
    default=["AAPL", "MSFT"]
)

weights = []
if tickers:
    st.sidebar.write("Pesos del portafolio:")
    for t in tickers:
        w = st.sidebar.number_input(f"{t}", min_value=0.0, max_value=1.0, value=1/len(tickers))
        weights.append(w)
weights = np.array(weights)

inicial = st.sidebar.number_input("Inversión inicial ($):", value=100000)

start = st.sidebar.date_input("Fecha inicial", pd.to_datetime("2020-01-01"))
end = st.sidebar.date_input("Fecha final", pd.to_datetime("2024-12-31"))

freq = st.sidebar.selectbox(
    "Frecuencia",
    {"1d": "Diaria", "1wk": "Semanal", "1mo": "Mensual"}
)

run = st.sidebar.button("Ejecutar análisis")

# ======================================================
# INTERFAZ PRINCIPAL
# ======================================================

st.title("Análisis Profesional de Portafolio")

if run:

    if abs(weights.sum() - 1) > 0.001:
        st.error("Los pesos deben sumar 1.")
        st.stop()

    data = descargar_data(tickers, start, end, freq)
    retornos, port_ret = calcular_retorno_portafolio(data, weights)
    ret_acum, vol_anual, sharpe = metricas_portafolio(port_ret)

    # =============================
    # MÉTRICAS EN TARJETAS
    # =============================
    st.subheader("Resumen del Portafolio")
    col1, col2, col3 = st.columns(3)

    col1.metric("Retorno Acumulado", f"{ret_acum:.2%}")
    col2.metric("Volatilidad Anualizada", f"{vol_anual:.2%}")
    col3.metric("Sharpe Ratio", f"{sharpe:.2f}")

    # =============================
    # PESTAÑAS
    # =============================
    tab1, tab2, tab3, tab4 = st.tabs([
        "📈 Precios",
        "📊 Retornos",
        "💲 Valor del Portafolio",
        "🔗 Correlaciones"
    ])

    # ----- TAB 1: PRECIOS -----
    with tab1:
        st.subheader("Serie de tiempo – Precios Ajustados")
        st.line_chart(data)

    # ----- TAB 2: RETORNOS -----
    with tab2:
        st.subheader("Retornos Acumulados")
        cum = (1 + port_ret).cumprod()
        st.line_chart(cum)

    # ----- TAB 3: EVOLUCIÓN DEL VALOR -----
    with tab3:
        st.subheader("Evolución del valor monetario")
        valor = inicial * cum
        st.line_chart(valor)

    # ----- TAB 4: CORRELACIONES -----
    with tab4:
        st.subheader("Matriz de Correlación")
        st.dataframe(retornos.corr())

else:
    st.info("Ajusta los parámetros en la barra lateral y ejecuta el análisis.")