# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ymxWfPkHPR_gztBdJVynoftFiWj0u164
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

# -----------------------------
# Funciones
# -----------------------------

def descargar_data(tickers, start, end, freq):
    data = yf.download(tickers, start=start, end=end, interval=freq)["Adj Close"]
    return data

def calcular_retorno_portafolio(data, weights):
    retornos = data.pct_change().dropna()
    port_ret = retornos.dot(weights)
    return retornos, port_ret

def metricas_portafolio(port_ret):
    ret_acum = (1 + port_ret).prod() - 1
    vol_anual = port_ret.std() * np.sqrt(252)
    sharpe = (port_ret.mean() * 252) / (port_ret.std() * np.sqrt(252))
    return ret_acum, vol_anual, sharpe

# -----------------------------
# Interfaz Streamlit
# -----------------------------

st.title("Demo Portafolio – Streamlit")

st.subheader("Parámetros de entrada")

# ---- Selección de acciones ----
tickers = st.multiselect(
    "Selecciona acciones:",
    ["AAPL", "MSFT", "AMZN", "GOOGL", "META", "TSLA", "NVDA"],
    default=["AAPL", "MSFT"]
)

# ---- Pesos ----
if tickers:
    st.write("Asigna los pesos (deben sumar 1):")
    weights = []
    for t in tickers:
        w = st.number_input(f"Peso para {t}", min_value=0.0, max_value=1.0, value=1/len(tickers))
        weights.append(w)
    weights = np.array(weights)

# ---- Inversión inicial ----
inicial = st.number_input("Inversión inicial ($):", value=100000)

# ---- Fechas ----
start = st.date_input("Fecha inicial", pd.to_datetime("2020-01-01"))
end = st.date_input("Fecha final", pd.to_datetime("2024-12-31"))

# ---- Frecuencia ----
freq = st.selectbox(
    "Frecuencia temporal:",
    {"1d": "Diaria", "1wk": "Semanal", "1mo": "Mensual"}
)

# -----------------------------
# Procesar datos
# -----------------------------

if st.button("Ejecutar análisis"):

    if abs(weights.sum() - 1) > 0.001:
        st.error("Los pesos no suman 1.")
        st.stop()

    data = descargar_data(tickers, start, end, freq)
    st.subheader("Serie de precios")
    st.line_chart(data)

    retornos, port_ret = calcular_retorno_portafolio(data, weights)
    ret_acum, vol_anual, sharpe = metricas_portafolio(port_ret)

    # -----------------------------
    # Mostrar métricas
    # -----------------------------
    st.subheader("Resultados del Portafolio")

    col1, col2, col3 = st.columns(3)
    col1.metric("Retorno Acumulado", f"{ret_acum:.2%}")
    col2.metric("Volatilidad Anualizada", f"{vol_anual:.2%}")
    col3.metric("Sharpe Ratio", f"{sharpe:.2f}")

    # -----------------------------
    # Retornos acumulados
    # -----------------------------
    st.subheader("Retornos Acumulados")
    cum = (1 + port_ret).cumprod()
    st.line_chart(cum)

    # -----------------------------
    # Evolución del valor del portafolio
    # -----------------------------
    st.subheader("Evolución del Valor del Portafolio")
    valor = inicial * cum
    st.line_chart(valor)

    # -----------------------------
    # Heatmap de correlaciones (simplificado)
    # -----------------------------
    st.subheader("Correlación entre activos")
    st.dataframe(retornos.corr())

    st.success("Análisis completo.")